/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteRouteImport } from './routes/cart/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as blankCheckoutRouteImport } from './routes/(blank)/checkout'
import { Route as blankOrderIndexRouteImport } from './routes/(blank)/order/index'
import { Route as blankOrderSuccessRouteImport } from './routes/(blank)/order/success'
import { Route as blankauthSignupRouteImport } from './routes/(blank)/(auth)/signup'
import { Route as blankauthSigninRouteImport } from './routes/(blank)/(auth)/signin'
import { Route as appProductsIdRouteImport } from './routes/(app)/products/$id'
import { Route as appCollectionsIdRouteImport } from './routes/(app)/collections/$id'

const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CartRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const blankCheckoutRoute = blankCheckoutRouteImport.update({
  id: '/(blank)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const blankOrderIndexRoute = blankOrderIndexRouteImport.update({
  id: '/(blank)/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const blankOrderSuccessRoute = blankOrderSuccessRouteImport.update({
  id: '/(blank)/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const blankauthSignupRoute = blankauthSignupRouteImport.update({
  id: '/(blank)/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const blankauthSigninRoute = blankauthSigninRouteImport.update({
  id: '/(blank)/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsIdRoute = appProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCollectionsIdRoute = appCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/cart': typeof CartRouteRouteWithChildren
  '/checkout': typeof blankCheckoutRoute
  '/cart/': typeof CartIndexRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/signin': typeof blankauthSigninRoute
  '/signup': typeof blankauthSignupRoute
  '/order/success': typeof blankOrderSuccessRoute
  '/order': typeof blankOrderIndexRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof blankCheckoutRoute
  '/': typeof appIndexRoute
  '/cart': typeof CartIndexRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/signin': typeof blankauthSigninRoute
  '/signup': typeof blankauthSignupRoute
  '/order/success': typeof blankOrderSuccessRoute
  '/order': typeof blankOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/cart': typeof CartRouteRouteWithChildren
  '/(blank)/checkout': typeof blankCheckoutRoute
  '/(app)/': typeof appIndexRoute
  '/cart/': typeof CartIndexRoute
  '/(app)/collections/$id': typeof appCollectionsIdRoute
  '/(app)/products/$id': typeof appProductsIdRoute
  '/(blank)/(auth)/signin': typeof blankauthSigninRoute
  '/(blank)/(auth)/signup': typeof blankauthSignupRoute
  '/(blank)/order/success': typeof blankOrderSuccessRoute
  '/(blank)/order/': typeof blankOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/cart/'
    | '/collections/$id'
    | '/products/$id'
    | '/signin'
    | '/signup'
    | '/order/success'
    | '/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/'
    | '/cart'
    | '/collections/$id'
    | '/products/$id'
    | '/signin'
    | '/signup'
    | '/order/success'
    | '/order'
  id:
    | '__root__'
    | '/(app)'
    | '/cart'
    | '/(blank)/checkout'
    | '/(app)/'
    | '/cart/'
    | '/(app)/collections/$id'
    | '/(app)/products/$id'
    | '/(blank)/(auth)/signin'
    | '/(blank)/(auth)/signup'
    | '/(blank)/order/success'
    | '/(blank)/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  CartRouteRoute: typeof CartRouteRouteWithChildren
  blankCheckoutRoute: typeof blankCheckoutRoute
  blankauthSigninRoute: typeof blankauthSigninRoute
  blankauthSignupRoute: typeof blankauthSignupRoute
  blankOrderSuccessRoute: typeof blankOrderSuccessRoute
  blankOrderIndexRoute: typeof blankOrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof CartRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(blank)/checkout': {
      id: '/(blank)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof blankCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blank)/order/': {
      id: '/(blank)/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof blankOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blank)/order/success': {
      id: '/(blank)/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof blankOrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blank)/(auth)/signup': {
      id: '/(blank)/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof blankauthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blank)/(auth)/signin': {
      id: '/(blank)/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof blankauthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/$id': {
      id: '/(app)/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof appProductsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collections/$id': {
      id: '/(app)/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof appCollectionsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appCollectionsIdRoute: typeof appCollectionsIdRoute
  appProductsIdRoute: typeof appProductsIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appCollectionsIdRoute: appCollectionsIdRoute,
  appProductsIdRoute: appProductsIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface CartRouteRouteChildren {
  CartIndexRoute: typeof CartIndexRoute
}

const CartRouteRouteChildren: CartRouteRouteChildren = {
  CartIndexRoute: CartIndexRoute,
}

const CartRouteRouteWithChildren = CartRouteRoute._addFileChildren(
  CartRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  CartRouteRoute: CartRouteRouteWithChildren,
  blankCheckoutRoute: blankCheckoutRoute,
  blankauthSigninRoute: blankauthSigninRoute,
  blankauthSignupRoute: blankauthSignupRoute,
  blankOrderSuccessRoute: blankOrderSuccessRoute,
  blankOrderIndexRoute: blankOrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
