/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as blankCheckoutRouteImport } from './routes/(blank)/checkout'
import { Route as appCartRouteImport } from './routes/(app)/cart'
import { Route as blankauthSignupRouteImport } from './routes/(blank)/(auth)/signup'
import { Route as blankauthSigninRouteImport } from './routes/(blank)/(auth)/signin'
import { Route as appProductsIdRouteImport } from './routes/(app)/products/$id'
import { Route as appCollectionsIdRouteImport } from './routes/(app)/collections/$id'
import { Route as blankOrderSuccessIndexRouteImport } from './routes/(blank)/order/success/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const blankCheckoutRoute = blankCheckoutRouteImport.update({
  id: '/(blank)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const appCartRoute = appCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => appRouteRoute,
} as any)
const blankauthSignupRoute = blankauthSignupRouteImport.update({
  id: '/(blank)/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const blankauthSigninRoute = blankauthSigninRouteImport.update({
  id: '/(blank)/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsIdRoute = appProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCollectionsIdRoute = appCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const blankOrderSuccessIndexRoute = blankOrderSuccessIndexRouteImport.update({
  id: '/(blank)/order/success/',
  path: '/order/success/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/cart': typeof appCartRoute
  '/checkout': typeof blankCheckoutRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/signin': typeof blankauthSigninRoute
  '/signup': typeof blankauthSignupRoute
  '/order/success': typeof blankOrderSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/cart': typeof appCartRoute
  '/checkout': typeof blankCheckoutRoute
  '/': typeof appIndexRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/signin': typeof blankauthSigninRoute
  '/signup': typeof blankauthSignupRoute
  '/order/success': typeof blankOrderSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/cart': typeof appCartRoute
  '/(blank)/checkout': typeof blankCheckoutRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/collections/$id': typeof appCollectionsIdRoute
  '/(app)/products/$id': typeof appProductsIdRoute
  '/(blank)/(auth)/signin': typeof blankauthSigninRoute
  '/(blank)/(auth)/signup': typeof blankauthSignupRoute
  '/(blank)/order/success/': typeof blankOrderSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/collections/$id'
    | '/products/$id'
    | '/signin'
    | '/signup'
    | '/order/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/checkout'
    | '/'
    | '/collections/$id'
    | '/products/$id'
    | '/signin'
    | '/signup'
    | '/order/success'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/cart'
    | '/(blank)/checkout'
    | '/(app)/'
    | '/(app)/collections/$id'
    | '/(app)/products/$id'
    | '/(blank)/(auth)/signin'
    | '/(blank)/(auth)/signup'
    | '/(blank)/order/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  blankCheckoutRoute: typeof blankCheckoutRoute
  blankauthSigninRoute: typeof blankauthSigninRoute
  blankauthSignupRoute: typeof blankauthSignupRoute
  blankOrderSuccessIndexRoute: typeof blankOrderSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(blank)/checkout': {
      id: '/(blank)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof blankCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/cart': {
      id: '/(app)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof appCartRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(blank)/(auth)/signup': {
      id: '/(blank)/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof blankauthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blank)/(auth)/signin': {
      id: '/(blank)/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof blankauthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/$id': {
      id: '/(app)/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof appProductsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collections/$id': {
      id: '/(app)/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof appCollectionsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(blank)/order/success/': {
      id: '/(blank)/order/success/'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof blankOrderSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appCartRoute: typeof appCartRoute
  appIndexRoute: typeof appIndexRoute
  appCollectionsIdRoute: typeof appCollectionsIdRoute
  appProductsIdRoute: typeof appProductsIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appCartRoute: appCartRoute,
  appIndexRoute: appIndexRoute,
  appCollectionsIdRoute: appCollectionsIdRoute,
  appProductsIdRoute: appProductsIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  blankCheckoutRoute: blankCheckoutRoute,
  blankauthSigninRoute: blankauthSigninRoute,
  blankauthSignupRoute: blankauthSignupRoute,
  blankOrderSuccessIndexRoute: blankOrderSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
