/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as blankRouteRouteImport } from './routes/(blank)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appSignupRouteImport } from './routes/(app)/signup'
import { Route as appCartRouteImport } from './routes/(app)/cart'
import { Route as appAccountRouteRouteImport } from './routes/(app)/account/route'
import { Route as blankCheckoutIndexRouteImport } from './routes/(blank)/checkout/index'
import { Route as blankCheckoutSuccessRouteImport } from './routes/(blank)/checkout/success'
import { Route as appProductsIdRouteImport } from './routes/(app)/products/$id'
import { Route as appContentsIdRouteImport } from './routes/(app)/contents/$id'
import { Route as appCollectionsIdRouteImport } from './routes/(app)/collections/$id'
import { Route as appAccountInfoRouteImport } from './routes/(app)/account/info'

const blankRouteRoute = blankRouteRouteImport.update({
  id: '/(blank)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSignupRoute = appSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => appRouteRoute,
} as any)
const appCartRoute = appCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => appRouteRoute,
} as any)
const appAccountRouteRoute = appAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => appRouteRoute,
} as any)
const blankCheckoutIndexRoute = blankCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => blankRouteRoute,
} as any)
const blankCheckoutSuccessRoute = blankCheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => blankRouteRoute,
} as any)
const appProductsIdRoute = appProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appContentsIdRoute = appContentsIdRouteImport.update({
  id: '/contents/$id',
  path: '/contents/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCollectionsIdRoute = appCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appAccountInfoRoute = appAccountInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => appAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof appAccountRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/signup': typeof appSignupRoute
  '/': typeof appIndexRoute
  '/account/info': typeof appAccountInfoRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/contents/$id': typeof appContentsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/checkout/success': typeof blankCheckoutSuccessRoute
  '/checkout': typeof blankCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof appAccountRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/signup': typeof appSignupRoute
  '/': typeof appIndexRoute
  '/account/info': typeof appAccountInfoRoute
  '/collections/$id': typeof appCollectionsIdRoute
  '/contents/$id': typeof appContentsIdRoute
  '/products/$id': typeof appProductsIdRoute
  '/checkout/success': typeof blankCheckoutSuccessRoute
  '/checkout': typeof blankCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(blank)': typeof blankRouteRouteWithChildren
  '/(app)/account': typeof appAccountRouteRouteWithChildren
  '/(app)/cart': typeof appCartRoute
  '/(app)/signup': typeof appSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/account/info': typeof appAccountInfoRoute
  '/(app)/collections/$id': typeof appCollectionsIdRoute
  '/(app)/contents/$id': typeof appContentsIdRoute
  '/(app)/products/$id': typeof appProductsIdRoute
  '/(blank)/checkout/success': typeof blankCheckoutSuccessRoute
  '/(blank)/checkout/': typeof blankCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/cart'
    | '/signup'
    | '/'
    | '/account/info'
    | '/collections/$id'
    | '/contents/$id'
    | '/products/$id'
    | '/checkout/success'
    | '/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/cart'
    | '/signup'
    | '/'
    | '/account/info'
    | '/collections/$id'
    | '/contents/$id'
    | '/products/$id'
    | '/checkout/success'
    | '/checkout'
  id:
    | '__root__'
    | '/(app)'
    | '/(blank)'
    | '/(app)/account'
    | '/(app)/cart'
    | '/(app)/signup'
    | '/(app)/'
    | '/(app)/account/info'
    | '/(app)/collections/$id'
    | '/(app)/contents/$id'
    | '/(app)/products/$id'
    | '/(blank)/checkout/success'
    | '/(blank)/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  blankRouteRoute: typeof blankRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(blank)': {
      id: '/(blank)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof blankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/signup': {
      id: '/(app)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof appSignupRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cart': {
      id: '/(app)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof appCartRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/account': {
      id: '/(app)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appAccountRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(blank)/checkout/': {
      id: '/(blank)/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof blankCheckoutIndexRouteImport
      parentRoute: typeof blankRouteRoute
    }
    '/(blank)/checkout/success': {
      id: '/(blank)/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof blankCheckoutSuccessRouteImport
      parentRoute: typeof blankRouteRoute
    }
    '/(app)/products/$id': {
      id: '/(app)/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof appProductsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contents/$id': {
      id: '/(app)/contents/$id'
      path: '/contents/$id'
      fullPath: '/contents/$id'
      preLoaderRoute: typeof appContentsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collections/$id': {
      id: '/(app)/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof appCollectionsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/account/info': {
      id: '/(app)/account/info'
      path: '/info'
      fullPath: '/account/info'
      preLoaderRoute: typeof appAccountInfoRouteImport
      parentRoute: typeof appAccountRouteRoute
    }
  }
}

interface appAccountRouteRouteChildren {
  appAccountInfoRoute: typeof appAccountInfoRoute
}

const appAccountRouteRouteChildren: appAccountRouteRouteChildren = {
  appAccountInfoRoute: appAccountInfoRoute,
}

const appAccountRouteRouteWithChildren = appAccountRouteRoute._addFileChildren(
  appAccountRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAccountRouteRoute: typeof appAccountRouteRouteWithChildren
  appCartRoute: typeof appCartRoute
  appSignupRoute: typeof appSignupRoute
  appIndexRoute: typeof appIndexRoute
  appCollectionsIdRoute: typeof appCollectionsIdRoute
  appContentsIdRoute: typeof appContentsIdRoute
  appProductsIdRoute: typeof appProductsIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAccountRouteRoute: appAccountRouteRouteWithChildren,
  appCartRoute: appCartRoute,
  appSignupRoute: appSignupRoute,
  appIndexRoute: appIndexRoute,
  appCollectionsIdRoute: appCollectionsIdRoute,
  appContentsIdRoute: appContentsIdRoute,
  appProductsIdRoute: appProductsIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface blankRouteRouteChildren {
  blankCheckoutSuccessRoute: typeof blankCheckoutSuccessRoute
  blankCheckoutIndexRoute: typeof blankCheckoutIndexRoute
}

const blankRouteRouteChildren: blankRouteRouteChildren = {
  blankCheckoutSuccessRoute: blankCheckoutSuccessRoute,
  blankCheckoutIndexRoute: blankCheckoutIndexRoute,
}

const blankRouteRouteWithChildren = blankRouteRoute._addFileChildren(
  blankRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  blankRouteRoute: blankRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
